#!/bin/sh

CURWDIR="$(cd $(dirname $0) && pwd)"
TITLE="PPTP-VPN"
PROGRAM_NAME="app-pptp"
START_SHELL="/system/apps/tp/bin/start.sh"
CUSTOM_CONFIG_FILE="$CURWDIR/connected.conf"

APPS_CONFIG_DIR="/data/conf"
LAUNCHER_CONFIG_DIR="$APPS_CONFIG_DIR/launcher/conf.d"
LAUNCHER_CONFIG_FILE="$LAUNCHER_CONFIG_DIR/$PROGRAM_NAME.conf"

ICON="./res/normal.png"
PRESSED_ICON="./res/pressed.png"

PID_FILE="$CURWDIR/$PROGRAM_NAME.pid"
PKILL_BIN="/usr/bin/pkill"
INSTALL_BIN="/usr/bin/install"
REMOVE="/bin/rm -f"

usage() {
    echo "ERROR: action missing"
    echo "syntax: $0 <start|stop|restart|status|config|install|uninstall>"
    echo "example: $0 start"
}

start() {
    $CURWDIR/service.sh on
}

stop() {
    $CURWDIR/service.sh off
}

run() {
    $CURWDIR/service.sh run &
}

config() {
    echo "{" > "$PROGRAM_NAME.conf"
    echo "\"name\" :  \"$TITLE\"," >> "$PROGRAM_NAME.conf"
    echo "\"icon\" : \"$CURWDIR/$ICON\"," >> "$PROGRAM_NAME.conf"
    echo "\"iconPressed\" : \"$CURWDIR/$PRESSED_ICON\"," >> "$PROGRAM_NAME.conf"
    echo "\"exec\" : \"$CURWDIR/init run\"," >> "$PROGRAM_NAME.conf"
    echo "\"msgNum\" : 4" >> "$PROGRAM_NAME.conf"
    echo "}" >> "$PROGRAM_NAME.conf"

    $INSTALL_BIN -d $LAUNCHER_CONFIG_DIR
    $INSTALL_BIN "$PROGRAM_NAME.conf" "$LAUNCHER_CONFIG_FILE"
}

uninstall() {
    $REMOVE "$LAUNCHER_CONFIG_FILE"
}

# main
if [ $# -lt 1 ]; then
    usage
    exit 255
fi

case "$1" in
    "start" )
        start;;
    "stop" )
        stop;;
    "restart" )
        start
        stop;;
    "install" )
        config;;
    "uninstall" )
        uninstall;;
    "run" )
        run;;
    * )
        usage ;;
esac
