#!/bin/sh

logger -t app-pptp "ip-up started executing"

# 更改pptp连接状态为on
UP_FILE="/var/run/pptp_on"
echo 1 > $UP_FILE

# 更新应用界面
SERVICE_FILE=`cat /var/run/service_location_file 2>/dev/null`
$SERVICE_FILE update_ui

touch /var/dont_change_dns

local resolv=`readlink -f /etc/resolv.conf`
echo "nameserver 8.8.8.8" > $resolv

logger -t app-pptp "change dns to 8.8.8.8"


route add -net 0.0.0.0 netmask 0.0.0.0 $IFNAME